id: A4C3DA8CF
title: Prayer of Aspiration Incorporating the Eight Thoughts of Great Beings Who Follow
  the Way of the Mahāyāna
type: translation
pechas:
- IAD7E7F6B
- IF35D5551
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:56:32.475003
  last_modified_at: 2023-01-04 12:56:32.475006
  collections:
  - Lala Sonam Chödrup Series
  - Works of Tibetan Masters
alignment_to_base:
  IAD7E7F6B/2B28: DBA8
  IF35D5551/7277: DBA8
